# Generated by Django 2.2 on 2019-04-18 01:58

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.CharField(default=None, max_length=50, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('timed_out', 'timed_out')], default=None, max_length=15, null=True)),
                ('qualification_status', models.CharField(choices=[('active', 'active'), ('qualified', 'qualified')], default='active', max_length=15)),
                ('photo_verification_status', models.CharField(choices=[('in_progress', 'in_progress'), ('confirmed', 'confirmed'), ('failed', 'failed')], default='in_progress', max_length=15)),
                ('qualification_mark', django_fsm.FSMField(default=None, max_length=15, null=True)),
                ('completed', models.NullBooleanField()),
                ('percentagecomplete', models.IntegerField(default=0)),
                ('ami_status', models.CharField(default=None, max_length=15, null=True)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.Course')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.LitmosStudent')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('terminate_at', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_progress.TestSession')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stages', models.PositiveIntegerField(default=None, null=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('stage', models.PositiveIntegerField()),
                ('status', django_fsm.FSMField(default=None, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_progress.TestSession')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
    ]
