# Generated by Django 2.2 on 2019-04-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmTokenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LitmosModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=100, verbose_name='Module ID')),
                ('module_code', models.CharField(max_length=100, verbose_name='Module code')),
            ],
        ),
        migrations.CreateModel(
            name='LitmosStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='User name')),
                ('user_id', models.CharField(max_length=150, verbose_name='User ID')),
                ('first_name', models.CharField(default=None, max_length=150, null=True, verbose_name='Firs name')),
                ('last_name', models.CharField(default=None, max_length=150, null=True, verbose_name='Last name')),
                ('email', models.CharField(default=None, max_length=150, null=True, verbose_name='E-Mail')),
                ('is_confirm', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_login_at', models.DateTimeField(auto_now_add=True)),
                ('remaining_auth_attempts', models.IntegerField(default=5)),
                ('remaining_confirm_attempts', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentConfirmToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.LitmosStudent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.LitmosStudent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
