# Generated by Django 2.2 on 2019-04-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
        ('student_progress', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litmosstudent',
            name='course',
            field=models.ManyToManyField(default=None, null=True, through='student_progress.TestSession', to='trainer.Course'),
        ),
        migrations.AddField(
            model_name='litmosstudent',
            name='teams',
            field=models.ManyToManyField(default=None, null=True, to='trainer.Team'),
        ),
        migrations.AddField(
            model_name='litmosmodule',
            name='course',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.Course'),
        ),
        migrations.AddField(
            model_name='confirmtokenlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.LitmosStudent'),
        ),
    ]
